---
title: "day14.posneg"
output: html_document
date: "2023-04-14"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# libs dat

**data downloaded from:**    
- https://datasetsearch.research.google.com/search?src=0&query=taylor%20swift&docid=L2cvMTF0bjV4cTBsdw%3D%3D

**images from wikipedia:**    
- https://en.wikipedia.org/wiki/Midnights   
- https://en.wikipedia.org/wiki/Red_(Taylor_Swift_album)
- I adjusted the opacity in Illustrator for both images to 50%

```{r warning=FALSE, message=FALSE}
library(tidyverse)
library(psych)
library(data.table)
library(png)
library(grid)
library(cowplot)

tswift_import <- read.csv("Taylor Swift Spotify Data.csv")
tswift <- tswift_import
tswift <- tswift[c(33, 6, 27, 8:10, 13:18, 34)] # cols to keep
tswift[,c(1,3)] <- lapply(tswift[,c(1,3)], as.factor) # album name, track name factor
head(tswift) # see it

#### load album covers ####
midnts <- readPNG("Midnights.png")
red <- readPNG("Red.png")
```

# eda
## albums
```{r album eda}
# table(dat$album_name)
keep <- c("1989", "evermore", "Fearless", "folklore", "Lover", "Midnights", "Red", "reputation", "Speak Now", "Taylor Swift") # vec of standard 10
tswift <- tswift %>% filter(album_name %in% keep)  # keep those 10
tswift <- droplevels(tswift) # remove levels for other albums
table(tswift$album_name) # see it
# sort by year
tswift <- tswift %>% arrange(album_release_year)
rm(keep) # no longer need vector

pairs.panels(tswift[c( # get sense of shape and relationships 
  which(colnames(tswift)=="album_release_year"),
  which(colnames(tswift)=="danceability"), 
  which(colnames(tswift)=="energy"), 
  which(colnames(tswift)=="liveness"),
  which(colnames(tswift)=="valence"))])

# by(tswift[c(2,4:5,7:12)], tswift$album_name, cor) # cherry picking correlations for pos/neg day 15

describe(tswift[c(which(colnames(tswift)=="valence"), which(colnames(tswift)=="energy"), which(colnames(tswift)=="danceability"))]) # descriptives
```

# vis

```{r plots}
baseplot <-
  tswift %>% # data
  select(album_name, danceability, valence, energy) %>% # keep cols
  filter(album_name=="Red"|album_name=="Midnights") %>% # only these albums based on line 59
  pivot_longer(cols = valence:energy, # longer for facet
               names_to = "var") %>% 
  ggplot(aes(x=value, y=danceability, color=album_name)) + 
  geom_smooth(method = "lm", fullrange=TRUE, se=FALSE, linewidth=4)+ # make lines prettier
  scale_color_manual(values = c("#4e4466", "#8b1912"))+ # hex codes for midnights and red
  facet_grid(cols = vars(var)) + # facet by energy and valence
  theme_classic() + # remove grid lines
  theme(legend.position = "bottom") + # move legend
  labs(color="Album") # rename legend title

#### layer albums ####
png("day14.png", width=900)
grid.draw(gList(rasterGrob(midnts, width = unit(.46,"npc"), height = unit(.85,"npc"), # start with midnights image
                           x=unit(0.28, "npc"), y=unit(0.58, "npc")),
                rasterGrob(red, width = unit(.46,"npc"), height = unit(.85,"npc"), # add red image
                           x=unit(.77, "npc"), y=unit(0.58, "npc")),
                ggplotGrob(baseplot))) # then baseplot for pos/neg
dev.off()
```
